basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# SET THE NAMESPACE!
app_name = 'basic_app'

urlpatterns=[
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^RouterAdding/$',views.RouterAdding,name='RouterAdding'),
    url(r'^other/$',views.other,name='other'),
    url(r'^devicestatus/$',views.devicestatus,name='devicestatus'),

]

learning_templates/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls'))
]

basic_app/models.py
from django.db import models

# Create your models here.
class Class_Model_Model1(models.Model):
    router_name = models.CharField(max_length = 60,unique=True)
    mgtIP = models.CharField(max_length = 60)
    # licenselevel = models.CharField(max_length = 60)
    version = models.CharField(max_length = 60)
    cpu = models.CharField(max_length = 60)
    cpu_frequency = models.CharField(max_length = 60)
    architecture_name = models.CharField(max_length = 60)
    board_name = models.CharField(max_length = 60)
    alive = models.CharField(max_length = 60)

    def __str__(self):
        return self.router_name

basic_app/forms.py
from django import forms

class Class_Form_1(forms.Form):
    routerip = forms.CharField()
    username = forms.CharField()
    password = forms.CharField()

basic_app/views.py
from django.shortcuts import render
from basic_app.models import Class_Model_Model1
from basic_app import forms
from . import routeros_func
import time

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

def other(request):
    return render(request,'basic_app/other.html')


def RouterAdding(request):
    # routeros_func.Router1()
    form = forms.Class_Form_1()
    if request.method == 'POST':
        form = forms.Class_Form_1(request.POST)

        if form.is_valid():
            #do something here
            print ("validation success")
            print("routerIP: " + form.cleaned_data["routerip"])
            print("Username: " + form.cleaned_data["username"])
            print("Password: " + form.cleaned_data["password"])
            routeros_func.Router1(router_ip=form.cleaned_data["routerip"],
                                  username=form.cleaned_data["username"],
                                  password=form.cleaned_data["password"])
            print("Router informanation fetched")
            time.sleep(3)
            return render(request,'basic_app/devicestatus.html')

    return render(request,'basic_app/RouterAdding.html',{'form':form})

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

def devicestatus(request):
    devicestatus = Class_Model_Model1.objects.order_by('router_name')
    devicestatus_dict = {'device_status':devicestatus}
    return render(request,'basic_app/devicestatus.html',devicestatus_dict)

templates/basic_app/RouterAdding.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}

    <h1> please input below information to add a router</h1>

    <div class="container">
        <form method="post">
          {{form.as_p}}
          {% csrf_token %}
          <input type="submit" class = "btn btn-primary" name="" value="SUBMIT">
        </form>

    </div>


    {% endblock %}

templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>JS</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <!-- <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
        </ul>
      </div>
    </nav> -->
    <div class="container">

    <nav class="navbar navbar-default navbar-inverse">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">

          <a class="navbar-brand" href="{% url 'index' %}">JS</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'basic_app:devicestatus' %}">Device Status</a></li>

            <!-- <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li> -->
            <li><a class="navbar-link" href="{% url 'basic_app:RouterAdding' %}">RouterAdding</a></li>
            <!-- <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Tools-Ping</a></li> -->

          </ul>

        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>


    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}

    </div>


  </body>
</html>

templates/basic_app/devicestatus.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block%}

    <div class="panel panel-default" >
      <!-- Default panel contents -->
      <div class="panel-heading">Device Status</div>
      <div class="panel-body">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>

      <!-- Table -->
      {% if device_status %}

      <table class="table table-hover">
        <thead>
          <th>router_name</th>
          <th>mgtIP</th>
          <!-- <th>licenselevel</th> -->
          <th>version</th>
          <th>cpu</th>
          <th>cpu_frequency</th>
          <th>architecture_name</th>
          <th>board_name</th>
          <th>alive</th>
          <th>Details</th>
        </thead>

        {% for ds in device_status %}
        <tr>
          <td>{{ds.router_name}}</td>
          <td>{{ds.mgtIP}}</td>
          <!-- <td>{{ds.licenselevel}}</td> -->
          <td>{{ds.version}}</td>
          <td>{{ds.cpu}}</td>
          <td>{{ds.cpu_frequency}}</td>
          <td>{{ds.architecture_name}}</td>
          <td>{{ds.board_name}}</td>
          <td>{{ds.alive}}</td>
          <td><a href="{% url 'basic_app:RouterAdding' %}" class="btn btn-primary btn-lg btn-sm" role="button">Details</a></td>
        </tr>
        {% endfor %}

        {% endif %}

      </table>

    </div>



    {% endblock %}

templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block%}

    <div class="jumbotron">
      <h1>Welcome!</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
    </div>



    {% endblock %}

templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}

    <h1>Other Page</h1>
    

    {% endblock %}

templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Relative Urls</title>
  </head>
  <body>
    <h1>Welcome!</h1>
    <p>
      This page serves as an example of how to
      use relative urls with templates!
      This is the relative_url_templates.html file.
    </p>

    {# Here are the examples:#}
    {# Must set the app_name=basic_app variable inside the basic_app/urls.py#}
    <a href="{% url 'admin:index' %}">Link to Admin Page</a>

    <!-- <a href="{% url 'basic_app:other' %}">Link to other.html</a> -->


  </body>
</html>